# https://taskfile.dev
# docker run -v "D:\Traning golang\__practicum__\metriccollector\metriccollector:/app" gotests task unit-tests
version: '3'

silent: true
tasks:
  unit-tests:
    cmds:
      - echo "- Run unit tests"
      - |      
        go build -ldflags '-s -w -X main.buildVersion=1.0.0 -X main.buildDate=2023-01-23 -X main.buildCommit=0c2fs'  -o cmd/agent/agent cmd/agent/main.go
        go build -ldflags '-s -w -X main.buildVersion=1.0.0 -X main.buildDate=2023-01-23 -X main.buildCommit=0c2fs'  -o cmd/server/server cmd/server/main.go
        # Run your test commands
          SERVER_PORT=4444
          ADDRESS="localhost:${SERVER_PORT}"
          TEMP_FILE=4444
          metricstestbeta -test.v -test.run=^TestIteration11$ \
            -agent-binary-path=cmd/agent/agent \
            -binary-path=cmd/server/server \
            -database-dsn='postgres://postgres:postgres@postgres:5432/praktikum?sslmode=disable' \
            -server-port=$SERVER_PORT \
            -source-path=.

  static-tests:
    cmds:
    - echo "- Run static tests"
    - go vet -vettool=statictest ./...
  run-all:
    deps: [run-server, run-agent]
  run-server:
    cmds:
    - echo "Run server"
    - go run cmd/server/main.go -a localhost:3333
  run-agent:
    cmds:
    - echo "Run agent"
    - go run cmd/agent/main.go -a localhost:3333
