# https://taskfile.dev
version: '3'

silent: true
tasks:
  unit-tests:
    cmds:
      - echo "- Run unit tests"
      - |      
        go build -ldflags '-s -w -X main.buildVersion=1.0.0 -X main.buildDate=2023-01-23 -X main.buildCommit=0c2fs'  -o cmd/agent/agent cmd/agent/main.go
        go build -ldflags '-s -w -X main.buildVersion=1.0.0 -X main.buildDate=2023-01-23 -X main.buildCommit=0c2fs'  -o cmd/server/server cmd/server/main.go
        # Run your test commands

        metricstestbeta -test.v -test.run=^TestIteration1$ \
            -binary-path=cmd/server/server


        # metricstestbeta -test.v -test.run=^TestIteration1$ -binary-path=cmd/shortener/shortener
        # metricstestbeta -test.v -test.run=^TestIteration1$ -binary-path=cmd/shortener/shortener 
        # metricstestbeta -test.v -test.run=^TestIteration2$ -binary-path=cmd/shortener/shortener -source-path=.  
        # metricstestbeta -test.v -test.run=^TestIteration3$ -binary-path=cmd/shortener/shortener -source-path=. 
        # metricstestbeta -test.v -test.run=^TestIteration4$ -binary-path=cmd/shortener/shortener -server-port=8083
        # metricstestbeta -test.v -test.run=^TestIteration5$ -binary-path=cmd/shortener/shortener -server-port=8083
        # metricstestbeta -test.v -test.run=^TestIteration6$ -binary-path=cmd/shortener/shortener  -source-path=. -server-port=8083 
        # metricstestbeta -test.v -test.run=^TestIteration7$ -binary-path=cmd/shortener/shortener  -source-path=. -server-port=8083 
        # metricstestbeta -test.v -test.run=^TestIteration8$ -binary-path=cmd/shortener/shortener
  static-tests:
    cmds:
    - echo "- Run static tests"
    - go vet -vettool=statictest ./...
  run-all:
    deps: [run-server, run-agent]
  run-server:
    cmds:
    - echo "Run server"
    - go run cmd/server/main.go
  run-agent:
    cmds:
    - echo "Run agent"
    - go run cmd/agent/main.go
