version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: praktikum
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./postgresql-data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: test-service
    stop_grace_period: 30s  # увеличивает время до SIGKILL
    ports:
      - "8080:3333"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=3333
      # - SERVER_PORT=8080
    volumes:
      - ../:/app
    working_dir: /app
    command: >
      task static-tests
